export const colors = [
  { value: 'black', label: 'مشکی' },
  { value: 'white', label: 'سفید' },
  { value: 'light-blue', label: 'آبی کم رنگ' },
  { value: 'blue', label: 'آبی' },
  { value: 'navy-blue', label: 'سرمه ای' },
  { value: 'red', label: 'قرمز' },
  { value: 'crimson', label: 'زرشکی' },
  { value: 'green', label: 'سبز' },
  { value: 'yellow', label: 'زرد' },
  { value: 'pink', label: 'صورتی' },
  { value: 'purple', label: 'بنفش' },
  { value: 'orange', label: 'پرتغالی' },
  { value: 'olive', label: 'زیتونی' },
  { value: 'gray', label: 'خاکستری' },
  { value: 'gold', label: 'طلایی' },
  { value: 'silver', label: 'نقره ای' },
  { value: 'chocolate', label: 'شکلاتی' },
  { value: 'brown', label: 'قهوه ای' },
  { value: 'beige', label: 'بژ' },
  { value: 'khaki', label: 'خاکی' },
  { value: 'azure', label: 'لاجوردی' },
];
